name: Flutter CI

on:
  push:
    branches: [ main, test ]
  pull_request:


jobs:
  checkAndBuildApk:
    runs-on: ubuntu-latest
    steps:

    # checking out code of the repo
    - name: Checkout code
      uses: actions/checkout@v3

    # caching flutter sdk  
    - name: Cache Flutter Sdk
      uses: actions/cache@v3
      with:
        path: /opt/hostedtoolcache/flutter
        key: ${{ runner.os }}-flutter-sdk-3.29.0
        restore-keys: |
          ${{ runner.os }}-flutter-sdk-

    #downloading and setting up flutter  
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.29.0'

    # caching pub dependencies
    - name: Cache Dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.pub-cache
        key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.yaml') }}
        restore-keys: |
          ${{ runner.os }}-flutter-    

    # installing dependencies      
    - name: Install dependencies
      run: flutter pub get

    # static analysis of code       
    - name: Analyze Code
      run: flutter analyze

    # running test in test directory   
    - name: Run tests
      if: github.ref == 'refs/heads/main'
      run: flutter test

    # building release apk only if the commit is on main branch
    - name: Build Apk (only on main branch)
      if: github.ref == 'refs/heads/main'
      run: flutter build apk --release

    # uploading release apk only if the commit is on main branch and build succeed 
    - name: Upload Apk Artifact (only if build succeeds)
      if: github.ref == 'refs/heads/main' && success()
      uses: actions/upload-artifact@v4
      with:
        name: release-apk
        path: build/app/outputs/flutter-apk/app-release.apk

    # only runs when a pr is created    
    - name: PR only Step
      if: github.event_name == 'pull_request'
      run: echo "This runs only on pull request"

    # releasing the flutter release apk on Github  
    - name: Create Github Release
      if: github.ref == 'refs/heads/main'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v1.0.${{ github.run_number }}
        name: Release v1.0.${{ github.run_number }}
        files: build/app/outputs/flutter-apk/app-release.apk
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
