name: Flutter CI

on:
  push:
    branches: [ main, test ]
  pull_request:


jobs:
  checkAndBuildApk:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.29.0'

    - name: Cache Dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.pub-cache
        keys: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.yaml') }}
        restore-keys: |
          ${{ runner.os }}-flutter-    

    - name: Install dependencies
      run: flutter pub get

    - name: Analyze Code
      run: flutter analyze

    - name: Run tests
      run: flutter test

    - name: Build Apk (only on main branch)
      if: github.ref == 'refs/heads/main'
      run: flutter build apk --release

    - name: Upload Apk Artifact (only if build succeeds)
      if: github.ref == 'refs/heads/main' && success()
      uses: actions/upload-artifact@v4
      with:
        name: release-apk
        path: build/app/outputs/flutter-apk/app-release.apk

    - name: PR only Step
      if: github.event_name == 'pull_request'
      run: echo "This runs only on pull request"
