name: Flutter CI

on:
  push:
    branches: [main]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.0'

      - name: Install dependencies
        run: flutter pub get

  analyze:  
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - run: flutter analyze

  test:      
    runs-on: ubuntu-latest
    needs: analyze
    steps:
      - run: flutter test